[package]
name = "edrFerd"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.27"
flexi_logger = "0.28.0"
chrono = "0.4.41"
serde = { version = "1.0.219", features = ["serde_derive"] }
foldhash = "0.1.5"
tokio = "1.46.1"
axum = "0.8.4"
blake3 = "1.8.2"
